version: "3.8"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: bencyber-website-prod
